apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "<CHARTNAME>.fullname" . | quote }}
  labels:
    {{- include "<CHARTNAME>.main.labels" . | nindent 4 }}
  annotations:
    {{- include "<CHARTNAME>.main.annotations" . | nindent 4 }}
data:
  STAGE: {{ .Values.appConfig.stage | quote }}
  APP_NAME: {{ .Chart.Name | quote }}
  {{- with .Values.globalExtraEnvVarsCM }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.main.extraEnvVarsCM }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
