{{- if .Values.logging.enabled }}
{{- if $.Values.logging.vector.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "<CHARTNAME>.fullname" . }}-logging-tls"
  labels:
    {{- include "<CHARTNAME>.common.labels" . | nindent 4 }}
  annotations:
    {{- include "<CHARTNAME>.common.annotations" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
...
{{- end }}
{{- end }}
