---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "<CHARTNAME>.fullname" . | quote }}
  labels:
    {{- include "<CHARTNAME>.main.labels" . | nindent 4 }}
  annotations:
    {{- include "<CHARTNAME>.main.annotations" . | nindent 4 }}
    {{- include "<CHARTNAME>.checksumPodAnnotations" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "<CHARTNAME>.main.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.main.replicas }}
  strategy: {{- toYaml .Values.main.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "<CHARTNAME>.main.selectorLabels" . | nindent 8 }}
      annotations:
        {{- include "<CHARTNAME>.main.annotations" . | nindent 8 }}
        {{- include "<CHARTNAME>.checksumPodAnnotations" . | nindent 8 }}
    spec:
      {{- if .Values.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.pullSecret }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.main.podSecurityContext | nindent 8 }}
      containers:

        - name: "{{ .Values.main.appName }}"
          {{- if .Values.main.appCommand }}
          command: {{ .Values.main.appCommand }}
          {{- end }}
          {{- with .Values.main.lifecycleHooks }}
          lifecycle:
          {{- tpl . $ | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.pullPolicy | quote }}
          resources: {{- toYaml .Values.main.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: "{{ include "<CHARTNAME>.fullname" . }}"
            - secretRef:
                name: "{{ include "<CHARTNAME>.fullname" . }}"
          ports:
          {{- range .Values.main.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .ports.internal }}
              protocol: {{ .protocol }}
          {{- end }}
          volumeMounts:
            - name: "{{ include "<CHARTNAME>.fullname" . }}-logs"
              mountPath: {{ .Values.appConfig.log.dir | quote }}
          {{- if .Values.appConfig.extraFiles }}
            {{- range .Values.appConfig.extraFiles }}
            - name: "{{ include "<CHARTNAME>.fullname" $ }}-{{ .path | replace "/" "-" | replace "." "-" | trimAll "-" }}"
              mountPath: {{ .path | quote }}
              {{- if .readOnly }}
              readOnly: {{ .readOnly }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if .Values.main.probes.enabled }}
          {{- if .Values.main.probes.readiness }}
          readinessProbe: {{- toYaml .Values.main.probes.readiness | nindent 12 }}
          {{- end }}
          {{- if .Values.main.probes.liveness }}
          livenessProbe: {{- toYaml .Values.main.probes.liveness | nindent 12 }}
          {{- end }}
          {{- if .Values.main.probes.startup }}
          startupProbe: {{- toYaml .Values.main.probes.startup | nindent 12 }}
          {{- end }}
          {{- end }}

        {{- if .Values.logging.enabled }}
        {{- if .Values.logging.vector.enabled }}
        - name: "vector"
          image: "{{ .Values.logging.vector.image.registry }}/{{ .Values.logging.vector.image.name }}:{{ .Values.logging.vector.image.tag }}"
          resources:
            {{- toYaml .Values.logging.vector.resources | nindent 12 }}
          volumeMounts:
            - name: "{{ include "<CHARTNAME>.fullname" . }}-logs"
              mountPath: {{ .Values.appConfig.log.dir | quote }}
            - name: "vector-data"
              mountPath: {{ .Values.logging.vector.dataDir | quote }}
            - name: "config-volume-vector"
              mountPath: "/etc/vector/vector.toml"
              subPath: vector.toml
              readOnly: true
        {{- end }}
        {{- end }}

      volumes:
        - name: "{{ include "<CHARTNAME>.fullname" . }}-logs"
          emptyDir: {}

        {{- if .Values.logging.enabled }}
        {{- if .Values.logging.vector.enabled }}
        - name: "vector-data"
          emptyDir: {}
        - name: "config-volume-vector"
          configMap:
            name: "{{ include "<CHARTNAME>.fullname" . }}-logging"
            items:
              - key: vector.toml
                path: vector.toml
        {{- end }}
        {{- end }}

        {{- if .Values.appConfig.extraFiles }}
        {{- range .Values.appConfig.extraFiles }}
        {{- $extraFiles := . }}
        - name: "{{ include "<CHARTNAME>.fullname" $ }}-{{ .path | replace "/" "-" | replace "." "-" | trimAll "-" }}"
          secret:
            secretName: "{{ include "<CHARTNAME>.fullname" $ }}-extra-files-{{ .path | replace "/" "-" | replace "." "-" | trimAll "-" }}"
            items:
            {{- range .files }}
              - key: "{{ .name }}"
                path: "{{ .name }}"
            {{- end }}
        {{- end }}
        {{- end }}

      {{- if .Values.main.nodeSelector }}
      nodeSelector: {{ toYaml .Values.main.nodeSelector | nindent 8 }}
      {{- end }}

      {{- if .Values.main.affinity }}
      affinity: {{ toYaml .Values.main.affinity | nindent 8 }}
      {{- else }}
      affinity:
        {{- if .Values.main.affinity }}
        {{- toYaml .Values.main.affinity | nindent 8 }}
        {{- else }}
        {{- if eq .Values.main.podAntiAffinityPreset "soft" }}
        {{- include "<CHARTNAME>.main.podAntiAffinity.soft" . | nindent 8 }}
        {{- else if eq .Values.main.podAntiAffinityPreset "hard" }}
        {{- include "<CHARTNAME>.main.podAntiAffinity.hard" . | nindent 8 }}
        {{- end }}
        {{- end }}
      {{- end }}

      {{- if .Values.main.tolerations }}
      tolerations: {{ toYaml .Values.main.tolerations | nindent 8 }}
      {{- end }}
...