{{- if .Values.migrations.enabled }}

{{/* All data from the "main" Secret + additional parameters will be taken. */}}

{{- $config := include (print $.Template.BasePath "/main-secret.yaml") . | fromYaml }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHARTNAME>.fullname" $ }}-migrations
  labels:
    {{- include "<CHARTNAME>.labels" $ | nindent 4 }}
    app.kubernetes.io/component: migrations
  annotations:
    {{- include "<CHARTNAME>.migrations.configAnnotations" . | nindent 4 }}
stringData:
  {{- $config.stringData | toYaml | nindent 2 }}
  {{- with .Values.migrations.extraEnvVarsSecret }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
...
{{- end }}
