{{- if .Values.migrations.enabled }}

{{/* All data from the "main" ConfigMap + additional parameters will be taken. */}}

{{- $config := include (print $.Template.BasePath "/main-cm.yaml") . | fromYaml }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "<CHARTNAME>.fullname" $ }}-migrations
  labels:
    {{- include "<CHARTNAME>.labels" $ | nindent 4 }}
    app.kubernetes.io/component: migrations
  annotations:
    {{- include "<CHARTNAME>.migrations.configAnnotations" . | nindent 4 }}
data:
  {{- $config.data | toYaml | nindent 2 }}
  {{- with .Values.migrations.extraEnvVarsCM }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
...
{{- end }}
